name: Basic-LoginSystem
main: metowa1227\basic\loginsystem\plugin\LoginSystem
api: 3.12.2
version: 1.0
author: metowa1227
description: BasicSeries-LoginSystem

permissions:
    basic.loginsystem:
        default: op
        description: Allows to control all of functions in LoginSystem
        
        childlen:
            basic.loginsystem.command:
                default: true